"""Offline contract for CODE V TOR tolerancing.

This module deliberately does not run CODE V or claim a yield.  The installed
11.5 Tolerancing manual documents ``WBF PER``/``WBF MC`` worksheet-buffer
exports, but does not show their complete exported file grammar.  Parsing is
therefore fail-closed until a real batch export is captured and versioned.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from app.core.engines.codev_batch import ensure_buf_exp_safe_filename

TorMetric = Literal["mtf", "rms"]


@dataclass(frozen=True)
class TorToleranceTable:
    """Explicit, expert-ratified CODE V tolerance commands.

    An empty table is rejected: CODE V defaults must never silently become an
    Atelier manufacturing standard.
    """

    commands: tuple[str, ...]
    provenance: str


@dataclass(frozen=True)
class TorCompensators:
    commands: tuple[str, ...]
    provenance: str


@dataclass(frozen=True)
class TorMonteCarlo:
    trials: int
    seed: int | None = None


@dataclass(frozen=True)
class TorParseResult:
    status: Literal["unavailable"]
    provenance: Literal["unavailable"]
    reason: str


def _quote_codev_path(path: Path) -> str:
    return f'"{str(path).replace("/", "\\\\")}"'


def _validate_commands(commands: Sequence[str], name: str) -> None:
    if not commands:
        raise ValueError(f"{name} must be explicit and non-empty")
    if any(not command.strip() or "\n" in command or "\r" in command for command in commands):
        raise ValueError(f"{name} commands must be non-empty single lines")


def build_codev_tor_sequence(
    *,
    source_path: Path | str,
    performance_result_path: Path | str,
    monte_carlo_result_path: Path | str,
    tolerance_table: TorToleranceTable,
    compensators: TorCompensators,
    monte_carlo: TorMonteCarlo,
    metric: TorMetric,
    mtf_frequency_lp_per_mm: float | None = None,
) -> str:
    """Build a TOR batch sequence using documented worksheet-buffer output.

    Evidence: CODE V 11.5 Tolerancing Reference Manual, chapter 2, "Defining
    TOR Output": WBF PER exports performance summary, WBF MC exports trials,
    and NTR selects the trial count.  Exact batch behaviour remains a real-
    machine verification item; this pure builder performs no optical work.
    """

    source = Path(source_path)
    performance_path = Path(performance_result_path)
    mc_path = Path(monte_carlo_result_path)
    ensure_buf_exp_safe_filename(performance_path)
    ensure_buf_exp_safe_filename(mc_path)
    _validate_commands(tolerance_table.commands, "tolerance_table")
    _validate_commands(compensators.commands, "compensators")
    if not tolerance_table.provenance.strip() or not compensators.provenance.strip():
        raise ValueError("tolerance and compensator provenance must be non-empty")
    if monte_carlo.trials <= 0:
        raise ValueError("monte_carlo.trials must be positive")
    if metric == "mtf":
        if mtf_frequency_lp_per_mm is None or not math.isfinite(mtf_frequency_lp_per_mm):
            raise ValueError("finite mtf_frequency_lp_per_mm is required for MTF TOR")
        if mtf_frequency_lp_per_mm <= 0:
            raise ValueError("mtf_frequency_lp_per_mm must be positive")
    elif mtf_frequency_lp_per_mm is not None:
        raise ValueError("mtf_frequency_lp_per_mm is only valid for MTF TOR")

    lines = [
        "! Generated by app.core.engines.codev_tolerance; offline TOR contract.",
        f"! tolerance provenance: {tolerance_table.provenance}",
        f"! compensator provenance: {compensators.provenance}",
        "OUT NO",
        f"IN CV_MACRO:ZEMAXOS_TO_CV {_quote_codev_path(source)}",
        *tolerance_table.commands,
        *compensators.commands,
        "TOR",
    ]
    if metric == "mtf":
        lines.append(f"FRE {mtf_frequency_lp_per_mm:.12g}")
    lines.extend([f"NTR {monte_carlo.trials}", "CHT N", "WBF PER", "GO"])
    # The manual documents separate PER and MC buffer selections.  Re-running
    # GO after changing WBF is deliberately visible pending machine validation.
    lines.extend(
        [
            f"BUF EXP B1 {_quote_codev_path(performance_path)}",
            "BUF DEL B1",
            "WBF MC",
            "GO",
            f"BUF EXP B1 {_quote_codev_path(mc_path)}",
            "BUF DEL B1",
            "OUT YES",
            "EXI YES",
            "",
        ]
    )
    return "\n".join(lines)


def parse_codev_tor_exports(
    performance_result_path: Path | str,
    monte_carlo_result_path: Path | str,
) -> TorParseResult:
    """Fail closed until real CODE V 11.5 BUF EXP samples define the grammar."""

    performance_path = Path(performance_result_path)
    mc_path = Path(monte_carlo_result_path)
    missing = [str(path) for path in (performance_path, mc_path) if not path.is_file()]
    if missing:
        return TorParseResult(
            status="unavailable",
            provenance="unavailable",
            reason=f"TOR BUF EXP file missing: {', '.join(missing)}",
        )
    return TorParseResult(
        status="unavailable",
        provenance="unavailable",
        reason=(
            "CODE V 11.5 TOR BUF EXP grammar awaits a real-machine sample; "
            "no yield was parsed"
        ),
    )
