"""CODE V ZMX import smoke and ZMX fidelity comparison helpers."""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from pathlib import Path

from app.core.engines.codev_batch import (
    DEFAULT_CODEV_EXECUTABLE,
    CodeVBatchResult,
    run_codev_batch,
)
from app.core.prescription_table import PrescriptionTable, extract_prescription_table
from app.core.zmx_ingest import ZMX_AMMO_DIR, load_normalized_zmx

CODEV_ROUNDTRIP_RESULT_SCHEMA = "atelier-codev-roundtrip-v1"
DEFAULT_PATENT_ROUNDTRIP_SEED = "US20170003482A1.zmx"
EFL_REL_TOLERANCE_PCT = 2.0

_ROUNDTRIP_SEQUENCE_NAME = "atelier_codev_zmx_import.seq"
_ROUNDTRIP_RESULT_NAME = "atelier_codev_zmx_import.tsv"
_ROUNDTRIP_COMMAND_EXPORT_NAME = "atelier_codev_roundtrip_export.seq"
_VIGNETTING_ALIASES = {
    "VDX": "VDX",
    "VDXN": "VDX",
    "ZVDX": "VDX",
    "VDY": "VDY",
    "VDYN": "VDY",
    "ZVDY": "VDY",
}


@dataclass(frozen=True)
class CodeVZmxImportResult:
    """Structured facts from a CODE V import of one Zemax file."""

    batch: CodeVBatchResult
    source_zmx: Path
    command_export_path: Path

    @property
    def data(self) -> dict[str, str]:
        return self.batch.data

    @property
    def efl_y_mm(self) -> float:
        return float(self.data["efl_y_mm"])

    @property
    def max_image_height_y_mm(self) -> float:
        return float(self.data["max_image_height_y_mm"])


@dataclass(frozen=True)
class GlassRow:
    """Per-surface glass facts from zmx_ingest normalization."""

    surface_index: int
    glass: str | None
    nd: float
    vd: float


@dataclass(frozen=True)
class ZmxFidelityFacts:
    """Comparable facts extracted from a ZMX through zmx_ingest."""

    path: Path
    efl_mm: float
    glass_rows: tuple[GlassRow, ...]
    asphere_term_counts: dict[int, int]
    vignetting: dict[str, tuple[float, ...]]


@dataclass(frozen=True)
class ZmxRoundTripComparison:
    """Four-gate comparison between source and round-tripped ZMX files."""

    source: ZmxFidelityFacts
    exported: ZmxFidelityFacts
    efl_deviation_pct: float
    glass_mismatches: tuple[str, ...]
    asphere_term_mismatches: tuple[str, ...]
    vignetting_mismatches: tuple[str, ...]

    @property
    def efl_within_tolerance(self) -> bool:
        return self.efl_deviation_pct < EFL_REL_TOLERANCE_PCT

    @property
    def passed(self) -> bool:
        return (
            self.efl_within_tolerance
            and not self.glass_mismatches
            and not self.asphere_term_mismatches
            and not self.vignetting_mismatches
        )

    def describe(self) -> dict[str, object]:
        return {
            "source_zmx": str(self.source.path),
            "exported_zmx": str(self.exported.path),
            "efl_deviation_pct": self.efl_deviation_pct,
            "efl_within_2pct": self.efl_within_tolerance,
            "glass_mismatches": list(self.glass_mismatches),
            "asphere_term_mismatches": list(self.asphere_term_mismatches),
            "vignetting_mismatches": list(self.vignetting_mismatches),
            "passed": self.passed,
        }


def default_patent_roundtrip_seed() -> Path:
    """Return the selected patent seed for ENGINE-03c."""

    return ZMX_AMMO_DIR / DEFAULT_PATENT_ROUNDTRIP_SEED


def build_zmx_import_sequence(
    *,
    source_zmx: Path | str,
    result_path: Path | str,
    command_export_path: Path | str,
) -> str:
    """Build a CODE V macro that imports ZMX and writes explicit metrics TSV.

    CODE V 11.5 ships the official ``CV_MACRO:ZEMAXOS_TO_CV`` import macro. Its
    documented command-file export is ``WRL``; that artifact is intentionally
    labeled as a command export, not as a Zemax ZMX export.
    """

    source_zmx = Path(source_zmx)
    result_path = Path(result_path)
    command_export_path = Path(command_export_path)
    rows = (
        ("schema", f'"{CODEV_ROUNDTRIP_RESULT_SCHEMA}"'),
        ("status", '"ok"'),
        ("source_zmx", f'"{source_zmx.name}"'),
        ("efl_y_mm", "(EFY)"),
        ("max_image_height_y_mm", "^maximh"),
        ("num_surfaces", "(NUM S)"),
        ("num_fields", "(NUM F)"),
        ("native_zmx_export", '"unavailable_in_codev_11_5_docs"'),
        ("command_export_path", f'"{command_export_path.name}"'),
    )

    lines = [
        "! Generated by app.core.engines.codev_roundtrip.",
        "OUT NO",
        f"IN CV_MACRO:ZEMAXOS_TO_CV {_quote_codev_path(source_zmx)}",
        "^maximh == 0",
        "FOR ^f 1 (NUM F)",
        "  ^yh == (YRI F^f Z1)",
        "  IF ABSF(^yh) > ^maximh",
        "    ^maximh == ABSF(^yh)",
        "  END IF",
        "END FOR",
    ]
    for index, (key, value) in enumerate(rows, start=1):
        lines.append(f'BUF PUT B1 I{index} J1 "{key}"')
        lines.append(f"BUF PUT B1 I{index} J2 {value}")
    lines.extend(
        [
            f"BUF EXP B1 {_quote_codev_path(result_path)}",
            "BUF DEL B1",
            f"WRL {_quote_codev_path(command_export_path)}",
            "OUT YES",
            "EXI YES",
            "",
        ]
    )
    return "\n".join(lines)


def write_zmx_import_sequence(
    *,
    sequence_path: Path | str,
    source_zmx: Path | str,
    result_path: Path | str,
    command_export_path: Path | str,
) -> Path:
    """Write a CODE V ZMX import sequence and return its path."""

    sequence_path = Path(sequence_path)
    sequence_path.parent.mkdir(parents=True, exist_ok=True)
    sequence_path.write_text(
        build_zmx_import_sequence(
            source_zmx=source_zmx,
            result_path=result_path,
            command_export_path=command_export_path,
        ),
        encoding="ascii",
    )
    return sequence_path


def run_codev_zmx_import(
    *,
    source_zmx: Path | str,
    work_dir: Path | str,
    executable: Path | str = DEFAULT_CODEV_EXECUTABLE,
    timeout_seconds: float = 90.0,
    platform_name: str = os.name,
) -> CodeVZmxImportResult:
    """Import one ZMX into CODE V and export structured import facts."""

    source_zmx = Path(source_zmx)
    work_dir = Path(work_dir)
    sequence_path = work_dir / _ROUNDTRIP_SEQUENCE_NAME
    result_path = work_dir / _ROUNDTRIP_RESULT_NAME
    command_export_path = work_dir / _ROUNDTRIP_COMMAND_EXPORT_NAME
    for stale in (result_path, command_export_path):
        if stale.exists():
            stale.unlink()
    write_zmx_import_sequence(
        sequence_path=sequence_path,
        source_zmx=source_zmx,
        result_path=result_path,
        command_export_path=command_export_path,
    )
    batch = run_codev_batch(
        sequence_path=sequence_path,
        result_path=result_path,
        executable=executable,
        work_dir=work_dir,
        timeout_seconds=timeout_seconds,
        platform_name=platform_name,
        expected_schema=CODEV_ROUNDTRIP_RESULT_SCHEMA,
    )
    return CodeVZmxImportResult(
        batch=batch,
        source_zmx=source_zmx,
        command_export_path=command_export_path,
    )


def extract_zmx_fidelity_facts(path: Path | str) -> ZmxFidelityFacts:
    """Extract the four fidelity gates from a ZMX via the existing ingest path."""

    zmx_path = Path(path)
    optic = load_normalized_zmx(zmx_path)
    table = extract_prescription_table(optic, source_zmx=zmx_path)
    return ZmxFidelityFacts(
        path=zmx_path,
        efl_mm=float(optic.paraxial.f2()),
        glass_rows=_glass_rows(table),
        asphere_term_counts=_asphere_term_counts(table),
        vignetting=_parse_vignetting(zmx_path),
    )


def compare_roundtrip_zmx(
    source_zmx: Path | str,
    exported_zmx: Path | str,
    *,
    nd_abs_tol: float = 1e-6,
    vd_abs_tol: float = 1e-4,
) -> ZmxRoundTripComparison:
    """Compare source and round-tripped ZMX across the ENGINE-03c gates."""

    source = extract_zmx_fidelity_facts(source_zmx)
    exported = extract_zmx_fidelity_facts(exported_zmx)
    efl_deviation_pct = abs(exported.efl_mm - source.efl_mm) / abs(source.efl_mm) * 100.0
    return ZmxRoundTripComparison(
        source=source,
        exported=exported,
        efl_deviation_pct=efl_deviation_pct,
        glass_mismatches=_glass_mismatches(
            source.glass_rows,
            exported.glass_rows,
            nd_abs_tol=nd_abs_tol,
            vd_abs_tol=vd_abs_tol,
        ),
        asphere_term_mismatches=_dict_mismatches(
            "surface",
            source.asphere_term_counts,
            exported.asphere_term_counts,
        ),
        vignetting_mismatches=_dict_mismatches("vignetting", source.vignetting, exported.vignetting),
    )


def _glass_rows(table: PrescriptionTable) -> tuple[GlassRow, ...]:
    rows: list[GlassRow] = []
    for surface in table.surfaces:
        nd = surface.refractive_index_d
        vd = surface.abbe_number
        if nd is None or vd is None or math.isclose(nd, 1.0, abs_tol=1e-12):
            continue
        rows.append(GlassRow(surface.index, surface.glass, nd, vd))
    return tuple(rows)


def _asphere_term_counts(table: PrescriptionTable) -> dict[int, int]:
    return {
        surface.index: len(surface.asphere_coefficients)
        for surface in table.surfaces
        if surface.asphere_coefficients
    }


def _glass_mismatches(
    source: tuple[GlassRow, ...],
    exported: tuple[GlassRow, ...],
    *,
    nd_abs_tol: float,
    vd_abs_tol: float,
) -> tuple[str, ...]:
    source_by_surface = {row.surface_index: row for row in source}
    exported_by_surface = {row.surface_index: row for row in exported}
    mismatches: list[str] = []
    for surface_index in sorted(set(source_by_surface) | set(exported_by_surface)):
        left = source_by_surface.get(surface_index)
        right = exported_by_surface.get(surface_index)
        if left is None or right is None:
            mismatches.append(f"S{surface_index}: glass row missing")
            continue
        if abs(left.nd - right.nd) > nd_abs_tol or abs(left.vd - right.vd) > vd_abs_tol:
            mismatches.append(
                f"S{surface_index}: nd/vd {left.nd:.8g}/{left.vd:.8g} -> "
                f"{right.nd:.8g}/{right.vd:.8g}"
            )
    return tuple(mismatches)


def _dict_mismatches(
    label: str,
    source: dict[int, int] | dict[str, tuple[float, ...]],
    exported: dict[int, int] | dict[str, tuple[float, ...]],
) -> tuple[str, ...]:
    mismatches: list[str] = []
    for key in sorted(set(source) | set(exported), key=str):
        if source.get(key) != exported.get(key):
            mismatches.append(f"{label} {key}: {source.get(key)!r} -> {exported.get(key)!r}")
    return tuple(mismatches)


def _parse_vignetting(path: Path) -> dict[str, tuple[float, ...]]:
    values: dict[str, list[float]] = {"VDX": [], "VDY": []}
    for raw_line in _read_zmx_text(path).splitlines():
        parts = raw_line.strip().split()
        if not parts:
            continue
        canonical_key = _VIGNETTING_ALIASES.get(parts[0].upper())
        if canonical_key is None:
            continue
        values[canonical_key].extend(_float_tokens(parts[1:]))
    return {key: tuple(value) for key, value in values.items()}


def _read_zmx_text(path: Path) -> str:
    for encoding in ("utf-16", "utf-16-le", "utf-8-sig", "latin-1"):
        try:
            return path.read_text(encoding=encoding)
        except (OSError, UnicodeError):
            continue
    return path.read_text(errors="ignore")


def _float_tokens(tokens: list[str]) -> list[float]:
    values: list[float] = []
    for token in tokens:
        try:
            values.append(float(token))
        except ValueError:
            continue
    return values


def _quote_codev_path(path: Path) -> str:
    value = str(path)
    if any(char in value for char in ('"', "\r", "\n")):
        raise ValueError(f"CODE V path cannot contain quotes or newlines: {value!r}")
    return f'"{value}"'
