"""Lens patent retrieval store — abstract interface + mock implementation.

The abstract `LensPatentStore` lets the Wizard's RAG step call `.search(...)`
without knowing whether the backend is pgvector+BGE-M3 or a keyword mock.
v1 ships `MockLensPatentStore`; a `PgVectorLensPatentStore` lands when the
relay's embedding channel comes back or owner provisions a self-hosted
embedding service (see PROJECT.md §IV).

The mock's scoring is intentionally simple: tokenize query + each patent's
title/abstract/claim, then Jaccard overlap. Scenario filter narrows the
corpus before scoring. Good enough for a demo where the Wizard names a
clear scenario and the corpus is curated.
"""

from __future__ import annotations

import json
import re
from abc import ABC, abstractmethod
from functools import lru_cache
from pathlib import Path

from pydantic import BaseModel, Field

from app.core.lens_system import Scenario

# v2-02 real case library index (generated by scripts/generate_cases.py).
# store.py is app/core/rag/ → parents[2] is app/ → app/data/optical_cases/.
_CASE_INDEX_PATH = Path(__file__).resolve().parents[2] / "data" / "optical_cases" / "index.json"


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------


class LensPatentHit(BaseModel):
    id: str
    title: str
    abstract: str
    assignee: str
    score: float = Field(..., ge=0.0, le=1.0, description="Relevance in [0, 1]")
    source: str
    source_url: str


# ---------------------------------------------------------------------------
# Abstract interface
# ---------------------------------------------------------------------------


class LensPatentStore(ABC):
    """Search interface every backend (mock / pgvector / etc.) implements."""

    @abstractmethod
    def search(self, query: str, scenario: Scenario, top_k: int = 5) -> list[LensPatentHit]: ...

    @property
    @abstractmethod
    def backend_name(self) -> str: ...


# ---------------------------------------------------------------------------
# Seed corpus (small but realistic — Largan/Sunny smartphone tele patents)
# ---------------------------------------------------------------------------


_SEED_PATENTS: list[dict] = [
    {
        "id": "US20200333565A1",
        "title": "Optical Imaging Lens Assembly",
        "abstract": (
            "An optical imaging lens assembly includes seven lens elements "
            "with refractive power, arranged from object to image side. Suited "
            "for smartphone telephoto modules with EFL around 7 mm and F/# 2.4. "
            "First lens positive, alternating powers."
        ),
        "claim_excerpt": (
            "An optical imaging lens assembly comprising seven lens elements "
            "with refractive power, the first lens element with positive refractive "
            "power having a convex object-side surface in the paraxial region."
        ),
        "assignee": "Largan Precision Co., Ltd.",
        "scenarios": [Scenario.SMARTPHONE_TELEPHOTO],
        "source_url": "https://patents.google.com/patent/US20200333565A1",
    },
    {
        "id": "US20210311293A1",
        "title": "Imaging Lens Assembly and Electronic Device",
        "abstract": (
            "An imaging lens assembly with six lens elements yields a compact "
            "telephoto module for smartphone integration. EFL around 12 mm, "
            "designed for periscope folded optical path."
        ),
        "claim_excerpt": (
            "An imaging lens assembly comprising six lens elements with the first "
            "element of positive refractive power and a folded periscope arrangement."
        ),
        "assignee": "Largan Precision Co., Ltd.",
        "scenarios": [Scenario.SMARTPHONE_TELEPHOTO],
        "source_url": "https://patents.google.com/patent/US20210311293A1",
    },
    {
        "id": "US20220197099A1",
        "title": "Optical Imaging System",
        "abstract": (
            "Optical imaging system for compact electronic devices, TTL under 5 mm, "
            "wide aperture F/1.7. Five lens elements suited for smartphone wide-angle "
            "main camera modules."
        ),
        "claim_excerpt": "An optical imaging system comprising five lens elements.",
        "assignee": "Sunny Optical Technology (Group) Co., Ltd.",
        "scenarios": [Scenario.SMARTPHONE_WIDE, Scenario.SMARTPHONE_ULTRAWIDE],
        "source_url": "https://patents.google.com/patent/US20220197099A1",
    },
    {
        "id": "US20230015432A1",
        "title": "Compact Wide-Angle Lens for Smartphone",
        "abstract": (
            "Compact wide-angle lens assembly for smartphone main camera, 24 mm "
            "equivalent EFL, F/1.8, six element design with aspheric surfaces and "
            "low f-tan(θ) distortion for full-frame sensor coverage."
        ),
        "claim_excerpt": "An optical lens assembly for wide-angle smartphone imaging.",
        "assignee": "Genius Electronic Optical (GSEO)",
        "scenarios": [Scenario.SMARTPHONE_WIDE],
        "source_url": "https://patents.google.com/patent/US20230015432A1",
    },
    {
        "id": "US20210284651A1",
        "title": "Near-Eye Display Optical System for Augmented Reality",
        "abstract": (
            "Optical waveguide-based near-eye display for augmented reality glasses, "
            "field of view 40 degrees diagonal, eyebox 12 mm, weight under 8 g per eye. "
            "Freeform substrate with MicroLED projector."
        ),
        "claim_excerpt": "A near-eye display system comprising a freeform optical waveguide.",
        "assignee": "Magic Leap / generic AR research",
        "scenarios": [Scenario.AR_NEAR_EYE],
        "source_url": "https://patents.google.com/patent/US20210284651A1",
    },
]


# ---------------------------------------------------------------------------
# Mock implementation: keyword overlap
# ---------------------------------------------------------------------------


_TOKEN_RE = re.compile(r"[a-z0-9]+")


def _tokens(text: str) -> set[str]:
    return set(_TOKEN_RE.findall(text.lower()))


# Stop words to remove from queries (don't help relevance signal).
_STOP = frozenset(
    {
        "a",
        "an",
        "the",
        "for",
        "with",
        "of",
        "to",
        "in",
        "on",
        "and",
        "or",
        "i",
        "we",
        "want",
        "need",
        "design",
        "make",
        "build",
        "lens",
        "lenses",
        "optical",
        "system",
        "assembly",
        "element",
        "elements",
    }
)


def _significant_tokens(text: str) -> set[str]:
    return {t for t in _tokens(text) if t not in _STOP and len(t) > 2}


def _jaccard(a: set[str], b: set[str]) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


class MockLensPatentStore(LensPatentStore):
    """Keyword-overlap retrieval over a curated seed corpus.

    Two-step scoring:
    1. Filter corpus to patents whose `scenarios` list includes the requested
       scenario (cuts out obvious non-matches).
    2. Score remaining patents by Jaccard overlap between the query's
       significant tokens and each patent's title+abstract+claim tokens.
    """

    backend_name = "mock"  # type: ignore[assignment]

    def __init__(self, patents: list[dict] | None = None) -> None:
        self._patents = patents if patents is not None else _SEED_PATENTS
        # Pre-tokenize each patent for speed.
        self._patent_tokens: list[set[str]] = [
            _significant_tokens(f"{p['title']} {p['abstract']} {p['claim_excerpt']}")
            for p in self._patents
        ]

    def search(self, query: str, scenario: Scenario, top_k: int = 5) -> list[LensPatentHit]:
        if top_k <= 0:
            return []

        query_tokens = _significant_tokens(query)

        scored: list[tuple[float, dict]] = []
        for patent, ptoks in zip(self._patents, self._patent_tokens, strict=True):
            if scenario not in patent.get("scenarios", []):
                continue
            score = _jaccard(query_tokens, ptoks)
            scored.append((score, patent))

        # Stable sort by score desc.
        scored.sort(key=lambda x: x[0], reverse=True)

        hits: list[LensPatentHit] = []
        for score, p in scored[:top_k]:
            hits.append(
                LensPatentHit(
                    id=p["id"],
                    title=p["title"],
                    abstract=p["abstract"],
                    assignee=p["assignee"],
                    score=score,
                    source=self.backend_name,
                    source_url=p["source_url"],
                )
            )
        return hits


# ---------------------------------------------------------------------------
# Default store factory
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Real case library retrieval: nearest real production design by parameters
# ---------------------------------------------------------------------------


class RealLensCaseStore(LensPatentStore):
    """Retrieve the nearest real production design by parameter distance.

    Replaces the 5 hand-typed patent abstracts with the v2-02 case library: reads
    `app/data/optical_cases/index.json` and ranks by a min-max-normalized weighted
    Euclidean distance over (EFL, FOV, F#) within the requested scenario. Every
    hit points to a real, Optiland-verified design — not generic patent text.
    """

    backend_name = "real_case"  # type: ignore[assignment]

    # EFL dominates the design target; FOV next; F# least (it's the loosest spec).
    _W_EFL, _W_FOV, _W_FNUM = 0.5, 0.3, 0.2

    def __init__(self, index_path: Path | None = None) -> None:
        path = index_path if index_path is not None else _CASE_INDEX_PATH
        self._cases: list[dict] = json.loads(path.read_text()) if path.exists() else []
        # Per-scenario (min, max) for normalizing each parameter to [0, 1].
        self._norm: dict[str, dict[str, tuple[float, float]]] = {}
        for scen in {c["scenario"] for c in self._cases}:
            grp = [c for c in self._cases if c["scenario"] == scen]
            self._norm[scen] = {
                k: (min(c[k] for c in grp), max(c[k] for c in grp))
                for k in ("efl_mm", "fov_deg", "fnum")
            }

    def _distance(self, efl: float, fnum: float, fov: float, cand: dict) -> float:
        norm = self._norm[cand["scenario"]]

        def nd(key: str, target: float, value: float) -> float:
            lo, hi = norm[key]
            return 0.0 if hi == lo else (target - value) / (hi - lo)

        d_efl = nd("efl_mm", efl, cand["efl_mm"])
        d_fov = nd("fov_deg", fov, cand["fov_deg"])
        d_fnum = nd("fnum", fnum, cand["fnum"])
        return (self._W_EFL * d_efl**2 + self._W_FOV * d_fov**2 + self._W_FNUM * d_fnum**2) ** 0.5

    def _to_hit(self, cand: dict, score: float) -> LensPatentHit:
        mats = ", ".join(cand.get("materials", [])[:4])
        kind = cand["scenario"].replace("smartphone-", "")
        abstract = (
            f"{cand['n_pieces']}-element {kind} smartphone design. "
            f"EFL {cand['efl_mm']:.2f}mm, F/{cand['fnum']:.1f}, FOV {cand['fov_deg']:.0f}°, "
            f"image height {cand.get('image_height_mm', 0):.1f}mm. "
            f"{cand['n_imaging']} imaging elements + {cand['n_filter']} flat "
            f"filter/cover plate(s). Materials: {mats}. "
            f"Optiland-verified (EFL error {cand.get('efl_error_pct', 0):.1f}%)."
        )
        return LensPatentHit(
            id=cand["case_id"],
            title=(
                f"{cand['n_pieces']}P real design · EFL{cand['efl_mm']:.1f} "
                f"F{cand['fnum']:.1f} FOV{cand['fov_deg']:.0f}"
            ),
            abstract=abstract,
            assignee="Real production design (anonymized)",
            score=min(1.0, max(0.0, score)),
            source=self.backend_name,
            source_url="",
        )

    def search_by_params(
        self,
        efl_mm: float,
        fnum: float,
        fov_deg: float,
        scenario: Scenario,
        top_k: int = 5,
    ) -> list[LensPatentHit]:
        """Rank cases in the scenario by weighted parameter distance (nearest first)."""
        if top_k <= 0:
            return []
        cands = [c for c in self._cases if c["scenario"] == scenario.value]
        if not cands:
            return []
        cands.sort(key=lambda c: self._distance(efl_mm, fnum, fov_deg, c))
        return [
            self._to_hit(c, 1.0 / (1.0 + self._distance(efl_mm, fnum, fov_deg, c)))
            for c in cands[:top_k]
        ]

    _EFL_RE = re.compile(r"EFL\s*([\d.]+)", re.IGNORECASE)
    _FNUM_RE = re.compile(r"F/?\s*([\d.]+)", re.IGNORECASE)
    _FOV_RE = re.compile(r"FOV\s*([\d.]+)", re.IGNORECASE)

    def search(self, query: str, scenario: Scenario, top_k: int = 5) -> list[LensPatentHit]:
        """ABC entry point. Parse EFL/F#/FOV from the query and rank by distance.

        If the query lacks parseable numbers, fall back to the scenario's cases
        ordered by EFL (stable, score 0.5) so the endpoint always returns hits.
        """
        if top_k <= 0:
            return []
        efl = self._EFL_RE.search(query)
        fnum = self._FNUM_RE.search(query)
        fov = self._FOV_RE.search(query)
        if efl and fnum and fov:
            return self.search_by_params(
                float(efl.group(1)),
                float(fnum.group(1)),
                float(fov.group(1)),
                scenario,
                top_k,
            )
        cands = sorted(
            (c for c in self._cases if c["scenario"] == scenario.value),
            key=lambda c: c["efl_mm"],
        )
        return [self._to_hit(c, 0.5) for c in cands[:top_k]]


# ---------------------------------------------------------------------------
# Default store factory
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def get_default_store() -> LensPatentStore:
    """Return the active store.

    Uses the real case library when `index.json` exists and is non-empty
    (production / after generate_cases); falls back to the keyword mock so CI and
    fresh checkouts without generated cases still serve the /api/rag endpoint.
    """
    if _CASE_INDEX_PATH.exists() and _CASE_INDEX_PATH.stat().st_size > 0:
        return RealLensCaseStore()
    return MockLensPatentStore()
